// Generated by CoffeeScript 1.6.2
(function() {
  var GUID, act, guid;

  GUID = (function() {
    function GUID() {}

    GUID.prototype.s4 = function() {
      return Math.floor((1 + Math.random()) * 0x10000).toString(16).substring(1);
    };

    GUID.prototype.create = function() {
      return "" + (this.s4()) + (this.s4()) + "-" + (this.s4()) + "-" + (this.s4()) + "-" + (this.s4()) + "-" + (this.s4()) + (this.s4()) + (this.s4());
    };

    return GUID;

  })();

  guid = new GUID;

  act = function() {
    $('#fais').attr('src', 'http://localhost:1235/?shoot=False&move_x=-0.585790557602&move_y=-0.0782275326677&look_x=-0.702675762832&look_y=-0.314776947275&jump=True&rand=' + guid.create());
    return setTimeout(act, 100);
  };

  $(function() {
    return act();
  });

}).call(this);

/*
//@ sourceMappingURL=main.map
*/
